[package]
name = "guzuta"
version = "0.2.5"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
description = "Custom repository manager for ArchLinux pacman"
homepage = "https://github.com/eagletmt/guzuta"
repository = "https://github.com/eagletmt/guzuta"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.5"
clap = "2.22"
env_logger = "0.4"
flate2 = "0.2"
gpgme = "0.5"
hyper = "0.10"
log = "0.3"
rusoto = { version = "0.24", features = ["s3"] }
rust-crypto = "0.2"
rust-lzma = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
tar = "0.4"
tempdir = "0.3"
