[package]
name = "guzuta"
version = "0.2.7"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
description = "Custom repository manager for ArchLinux pacman"
homepage = "https://github.com/eagletmt/guzuta"
repository = "https://github.com/eagletmt/guzuta"
readme = "README.md"
license = "MIT"

[dependencies]
base64 = "0.5"
clap = "2.22"
env_logger = "0.4"
flate2 = "0.2"
gpgme = "0.5"
hyper = "0.10"
log = "0.3"
rusoto_core = "0.28"
rusoto_s3 = "0.28"
rust-crypto = "0.2"
rust-lzma = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
tar = "0.4"
tempdir = "0.3"
