[package]
name = "guzuta"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]
description = "Custom repository manager for ArchLinux pacman"
homepage = "https://github.com/eagletmt/guzuta"
repository = "https://github.com/eagletmt/guzuta"
readme = "README.md"
license = "MIT"

[dependencies]
clap = "2.19"
env_logger = "0.3"
flate2 = "0.2"
gpgme = "0.4"
hyper = "0.10"
log = "0.3"
rusoto = { version = "0.22", features = ["s3"] }
rust-crypto = "0.2"
rust-lzma = "0.2"
rustc-serialize = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_yaml = "0.5"
tar = "0.4"
tempdir = "0.3"
